sudo: required

language: node_js
node_js:
  - "4"

services:
  - docker

before_install:
  - docker build -t hello-docker .
  - docker run -d --rm --name hello-docker hello-docker
  - docker kill hello-docker
